Debug information for file: javali_tests\NotOwnTestCases\ErrNoSuchTypeMethod.javali
AST Resulting From Parsing Stage:
ClassDecl (name: Main, superClass: Object)
| MethodDecl (argumentNames: [], argumentTypes: [], name: main, returnType: void)
| | Seq ()
| | Seq ()
| MethodDecl (argumentNames: [], argumentTypes: [], name: method, returnType: A)
| | Seq ()
| | Seq ()
| MethodDecl (argumentNames: [], argumentTypes: [], name: f, returnType: boolean)
| | Seq ()
| | Seq ()
Error message from reference is: No type 'A' was found

Test failed because an exception was thrown:
    null
Stack trace:
java.lang.NullPointerException
	at cd.frontend.semantic.SymbolTable.print(SymbolTable.java:95)
	at cd.frontend.semantic.SemanticAnalyzer.check(SemanticAnalyzer.java:42)
	at cd.Main.semanticCheck(Main.java:111)
	at cd.test.AbstractTestAgainstFrozenReference.testSemanticAnalyzer(AbstractTestAgainstFrozenReference.java:145)
	at cd.test.AbstractTestAgainstFrozenReference.test(AbstractTestAgainstFrozenReference.java:50)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
